ALTER TABLE movie_likes
CHANGE isLike is_like BOOLEAN NOT NULL,
CHANGE createdAt created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
CHANGE updatedAt updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;